version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  postgres:
    <<: *logging

    image: "docker.io/postgres:16-alpine"

    ports:
    - "5432:5432"

    environment:
      POSTGRES_DB: xythrion
      POSTGRES_PASSWORD: xythrion
      POSTGRES_USER: xythrion

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xythrion"]
      interval: 2s
      timeout: 1s
      retries: 5

  adminer:
    <<: *logging

    image: "docker.io/adminer:latest"

    ports:
    - "8080:8080"

  api:
    <<: *logging

    build:
      context: ./api
      dockerfile: Dockerfile

    env_file:
    - .env

    environment:
      DATABASE_URL: postgresql://xythrion:xythrion@postgres:5432/xythrion

    volumes:
    - ./api:/api

    depends_on:
    - postgres

    ports:
    - "8001:8000"

  bot:
    <<: *logging

    build:
      context: ./xythrion
      dockerfile: Dockerfile

    environment:
      API_URL: "http://api:8001"

    env_file:
    - .env

    depends_on:
    - api

    volumes:
    - ./bot:/bot

  metabase:
    <<: *logging

    container_name: metabase

    image: "docker.io/metabase/metabase:latest"

    ports:
    - "3000:3000"

    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: xythrion
      MB_DB_USER: xythrion
      MB_DB_PASS: xythrion
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432

    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  grafana:
    <<: *logging

    container_name: grafana

    image: "docker.io/grafana/grafana"

    volumes:
    - ./services/grafana/dashboards:/etc/grafana/provisioning/dashboards/

    ports:
    - "3030:3000"

  prometheus:
    <<: *logging

    container_name: prometheus

    image: "docker.io/prom/prometheus"

    volumes:
    - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
    - "9090:9090"
